import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { ChartRenderer } from './ChartRenderer';
import { Sparkles, TrendingUp, AlertOctagon, FileText, Download, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
// @ts-ignore
import html2canvas from 'html2canvas';
// @ts-ignore
import { jsPDF } from 'jspdf';

interface AnalysisDashboardProps {
  result: AnalysisResult;
}

export const AnalysisDashboard: React.FC<AnalysisDashboardProps> = ({ result }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    const element = document.getElementById('analysis-dashboard-content');
    if (!element) {
      setIsDownloading(false);
      return;
    }

    try {
      // Small delay to ensure render stability before capture
      await new Promise(resolve => setTimeout(resolve, 100));

      const canvas = await html2canvas(element, {
        scale: 2, // Higher resolution
        backgroundColor: '#0f172a', // Match app background (slate-900)
        logging: false,
        useCORS: true
      });

      const imgData = canvas.toDataURL('image/png');
      // Create a PDF with a size matching the content aspect ratio (long page)
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width, canvas.height] 
      });

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      pdf.save('DeepAnalyze_Report.pdf');
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex justify-end mb-2">
        <button
          onClick={handleDownloadPDF}
          disabled={isDownloading}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-all shadow-lg hover:shadow-blue-500/20 text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isDownloading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>Generating PDF...</span>
            </>
          ) : (
            <>
              <Download className="w-4 h-4" />
              <span>Download Report</span>
            </>
          )}
        </button>
      </div>

      <div id="analysis-dashboard-content" className="space-y-6 p-4 bg-slate-900">
        {/* Summary Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 bg-slate-800 border border-slate-700 rounded-xl p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <FileText className="w-32 h-32 text-blue-500" />
            </div>
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-400" />
              Executive Summary
            </h2>
            <p className="text-slate-300 leading-relaxed text-lg">
              {result.summary}
            </p>
          </div>

          <div className="bg-slate-800 border border-slate-700 rounded-xl p-6">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-green-400" />
              Key Insights
            </h2>
            <ul className="space-y-3">
              {result.keyInsights.map((insight, idx) => (
                <li key={idx} className="flex items-start gap-3 text-slate-300">
                  <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-green-400 mt-2.5"></span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {result.charts.map((chart, idx) => (
            <ChartRenderer key={idx} config={chart} />
          ))}
        </div>

        {/* Detailed Report */}
        <div className="bg-slate-800 border border-slate-700 rounded-xl p-8">
          <h2 className="text-xl font-semibold text-white mb-6 border-b border-slate-700 pb-4">
            Detailed Analysis Report
          </h2>
          <div className="prose prose-invert prose-slate max-w-none">
            <ReactMarkdown>{result.rawAnalysis}</ReactMarkdown>
          </div>
        </div>
        
        <div className="text-center text-slate-600 text-xs mt-8 pt-4 border-t border-slate-800">
             Generated by DeepAnalyze-8B Web Demo
        </div>
      </div>
    </div>
  );
};