
import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { ChartRenderer } from './ChartRenderer';
import { Sparkles, TrendingUp, FileText, Download, Loader2, Cpu, Code, FileJson } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
// @ts-ignore
import html2canvas from 'html2canvas';
// @ts-ignore
import { jsPDF } from 'jspdf';

interface AnalysisDashboardProps {
  result: AnalysisResult;
  language: string;
}

const translations: Record<string, any> = {
  'Simplified Chinese': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'PDF 报告',
    generating: '生成中...',
    modelLatency: '模型延迟',
    input: '输入',
    output: '输出',
    total: '总计',
    executiveSummary: '执行摘要',
    keyInsights: '关键见解',
    detailedReport: '详细分析报告',
    generatedBy: '生成自 DeepAnalyze-8B Web Demo'
  },
  'English': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'PDF Report',
    generating: 'Generating...',
    modelLatency: 'Model Latency',
    input: 'Input',
    output: 'Output',
    total: 'Total',
    executiveSummary: 'Executive Summary',
    keyInsights: 'Key Insights',
    detailedReport: 'Detailed Analysis Report',
    generatedBy: 'Generated by DeepAnalyze-8B Web Demo'
  },
  'Japanese': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'PDFレポート',
    generating: '生成中...',
    modelLatency: 'モデル遅延',
    input: '入力',
    output: '出力',
    total: '合計',
    executiveSummary: 'エグゼクティブサマリー',
    keyInsights: '重要な洞察',
    detailedReport: '詳細分析レポート',
    generatedBy: 'DeepAnalyze-8B Web Demoによって生成'
  },
   'Korean': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'PDF 보고서',
    generating: '생성 중...',
    modelLatency: '모델 대기 시간',
    input: '입력',
    output: '출력',
    total: '합계',
    executiveSummary: '경영 요약',
    keyInsights: '주요 통찰력',
    detailedReport: '상세 분석 보고서',
    generatedBy: 'DeepAnalyze-8B 웹 데모에서 생성됨'
  },
  'Spanish': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'Informe PDF',
    generating: 'Generando...',
    modelLatency: 'Latencia Modelo',
    input: 'Entrada',
    output: 'Salida',
    total: 'Total',
    executiveSummary: 'Resumen Ejecutivo',
    keyInsights: 'Ideas Clave',
    detailedReport: 'Informe de Análisis Detallado',
    generatedBy: 'Generado por DeepAnalyze-8B Web Demo'
  },
  'French': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'Rapport PDF',
    generating: 'Génération...',
    modelLatency: 'Latence Modèle',
    input: 'Entrée',
    output: 'Sortie',
    total: 'Total',
    executiveSummary: 'Résumé Exécutif',
    keyInsights: 'Idées Clés',
    detailedReport: 'Rapport d\'Analyse Détaillé',
    generatedBy: 'Généré par DeepAnalyze-8B Web Demo'
  },
  'German': {
    json: 'JSON',
    markdown: 'Markdown',
    pdf: 'PDF Bericht',
    generating: 'Generiere...',
    modelLatency: 'Modell Latenz',
    input: 'Eingabe',
    output: 'Ausgabe',
    total: 'Gesamt',
    executiveSummary: 'Management Summary',
    keyInsights: 'Wichtige Erkenntnisse',
    detailedReport: 'Detaillierter Analysebericht',
    generatedBy: 'Erstellt von DeepAnalyze-8B Web Demo'
  }
};

export const AnalysisDashboard: React.FC<AnalysisDashboardProps> = ({ result, language }) => {
  const [isDownloadingPdf, setIsDownloadingPdf] = useState(false);
  const t = translations[language] || translations['English'];

  const handleDownloadPDF = async () => {
    setIsDownloadingPdf(true);
    const element = document.getElementById('analysis-dashboard-content');
    if (!element) {
      setIsDownloadingPdf(false);
      return;
    }

    try {
      await new Promise(resolve => setTimeout(resolve, 100));

      const canvas = await html2canvas(element, {
        scale: 2,
        backgroundColor: '#0f172a',
        logging: false,
        useCORS: true
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width, canvas.height] 
      });

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      pdf.save('DeepAnalyze_Report.pdf');
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsDownloadingPdf(false);
    }
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([result.rawAnalysis], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'DeepAnalyze_Report.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'DeepAnalyze_Full_Data.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex flex-wrap justify-end gap-2 mb-2">
         <button
          onClick={handleDownloadJSON}
          className="flex items-center gap-2 px-3 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 rounded-lg transition-all text-sm font-medium"
        >
          <FileJson className="w-4 h-4" />
          <span>{t.json}</span>
        </button>
        
        <button
          onClick={handleDownloadMarkdown}
          className="flex items-center gap-2 px-3 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 rounded-lg transition-all text-sm font-medium"
        >
          <Code className="w-4 h-4" />
          <span>{t.markdown}</span>
        </button>

        <button
          onClick={handleDownloadPDF}
          disabled={isDownloadingPdf}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-all shadow-lg hover:shadow-blue-500/20 text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isDownloadingPdf ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>{t.generating}</span>
            </>
          ) : (
            <>
              <Download className="w-4 h-4" />
              <span>{t.pdf}</span>
            </>
          )}
        </button>
      </div>

      <div id="analysis-dashboard-content" className="space-y-6 p-4 bg-slate-900 border border-slate-800 rounded-xl">
        {/* Token Usage Badge */}
        {result.usage && (
          <div className="flex items-center justify-end gap-4 text-xs font-mono text-slate-500 border-b border-slate-800 pb-2">
            <div className="flex items-center gap-1">
              <Cpu className="w-3 h-3" />
              <span>{t.modelLatency}: ~1.2s</span>
            </div>
            <div>
              <span className="text-slate-400">{t.input}:</span> {result.usage.promptTokens}
            </div>
            <div>
              <span className="text-slate-400">{t.output}:</span> {result.usage.outputTokens}
            </div>
            <div>
              <span className="text-blue-400 font-bold">{t.total}: {result.usage.totalTokens}</span>
            </div>
          </div>
        )}

        {/* Summary Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 bg-slate-800 border border-slate-700 rounded-xl p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <FileText className="w-32 h-32 text-blue-500" />
            </div>
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-400" />
              {t.executiveSummary}
            </h2>
            <p className="text-slate-300 leading-relaxed text-lg">
              {result.summary}
            </p>
          </div>

          <div className="bg-slate-800 border border-slate-700 rounded-xl p-6">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-green-400" />
              {t.keyInsights}
            </h2>
            <ul className="space-y-3">
              {result.keyInsights.map((insight, idx) => (
                <li key={idx} className="flex items-start gap-3 text-slate-300">
                  <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-green-400 mt-2.5"></span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {result.charts.map((chart, idx) => (
            <ChartRenderer key={idx} config={chart} />
          ))}
        </div>

        {/* Detailed Report */}
        <div className="bg-slate-800 border border-slate-700 rounded-xl p-8">
          <h2 className="text-xl font-semibold text-white mb-6 border-b border-slate-700 pb-4">
            {t.detailedReport}
          </h2>
          <div className="prose prose-invert prose-slate max-w-none">
            <ReactMarkdown>{result.rawAnalysis}</ReactMarkdown>
          </div>
        </div>
        
        <div className="text-center text-slate-600 text-xs mt-8 pt-4 border-t border-slate-800 flex justify-between">
             <span>{t.generatedBy}</span>
             <span>ID: {crypto.randomUUID().slice(0, 8)}</span>
        </div>
      </div>
    </div>
  );
};
